apiVersion: xl/v1
kind: Blueprint
metadata:
  projectName: Docker Demo Application
  description: |
    The blueprint deploys a simple application in 2 Docker containers into your local Docker setup.
    XL Deploy does the deployment, while XL Release orchestrates everything.
  author: XebiaLabs
  version: 1.0
spec:
  parameters:
  - name: AppName
    type: Input
    description: What is the Application name?
  - name: ContainerPort
    type: Input
    description: At what port should the application be exposed in the container?
    value: 80
  - name: HostPort
    type: Input
    description: At what port should the container port be mapped in the host?
    value: 8181
  - name: BackendDockerImage
    type: Input
    description: What is the Docker Image (repo and path) for the Backend service?
    default: xebialabsunsupported/rest-o-rant-api
  - name: FrontendDockerImage
    type: Input
    description: What is the Docker Image (repo and path) for the Frontend service?
    default: xebialabsunsupported/rest-o-rant-web
  - name: CACert
    type: Editor
    description: What is the CA certificate?
    saveInXlVals: true
  - name: UserCert
    type: File
    description: What is the filename for user certificate?
    saveInXlVals: true
    default: sample.crt

  files:
  - path: xebialabs/xld-environment.yaml.tmpl
  - path: xebialabs/xld-docker-apps.yaml.tmpl
  - path: xebialabs/xlr-pipeline.yaml.tmpl
  - path: xebialabs.yaml